-- MySQL Script generated by MySQL Workbench
-- Tue May  7 13:56:15 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_sistema
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_sistema` ;

-- -----------------------------------------------------
-- Schema bd_sistema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_sistema` DEFAULT CHARACTER SET utf8 ;
USE `bd_sistema` ;

-- -----------------------------------------------------
-- Table `bd_sistema`.`comunidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_sistema`.`comunidade` ;

CREATE TABLE IF NOT EXISTS `bd_sistema`.`comunidade` (
  `id_comunidade` INT NOT NULL AUTO_INCREMENT,
  `ativo` INT NOT NULL,
  `padroeiro` VARCHAR(45) NOT NULL,
  `localizacao` VARCHAR(45) NOT NULL,
  `foto` LONGBLOB NULL,
  PRIMARY KEY (`id_comunidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sistema`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_sistema`.`usuario` ;

CREATE TABLE IF NOT EXISTS `bd_sistema`.`usuario` (
  `cpf` BIGINT(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `id_comunidade` INT NOT NULL,
  `foto` LONGBLOB NULL,
  PRIMARY KEY (`cpf`),
    FOREIGN KEY (`id_comunidade`)
    REFERENCES `bd_sistema`.`comunidade` (`id_comunidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sistema`.`Login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_sistema`.`Login` ;

CREATE TABLE IF NOT EXISTS `bd_sistema`.`Login` (
  `senha` VARCHAR(45) NOT NULL,
  `perfil` INT NOT NULL,
  `usuario_cpf` BIGINT(11) NOT NULL,
    FOREIGN KEY (`usuario_cpf`)
    REFERENCES `bd_sistema`.`usuario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sistema`.`Avisos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_sistema`.`Avisos` ;

CREATE TABLE IF NOT EXISTS `bd_sistema`.`Avisos` (
  `id_avisos` INT NOT NULL AUTO_INCREMENT,
  `ativo` INT NOT NULL,
  `abrangencia` INT NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(300) NULL,
  `id_comunidade` INT NOT NULL,
  PRIMARY KEY (`id_avisos`),
    FOREIGN KEY (`id_comunidade`)
    REFERENCES `bd_sistema`.`comunidade` (`id_comunidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
